### PR TITLE
Upgrade to use Integer instead of Fixnum

### PR DESCRIPTION
**Pull request by taf2**
fixes for Ruby 2.4

### CODE REVIEW

**Comment by BrendaEgeland** [comment]
Pretty please merge this :-)

**Comment by gregawoods** [comment]
I'd love for the `Fixnum` warnings to go away in my application. There are multiple PRs out to address the issue (#109, #115). Any chance we can get one of them merged in?

**Comment by DaveTorbeck** [comment]
Any update on this PR?  Would love for this to go through.

**Comment by adavidw** [comment]
I just merged PR #109 to resolve this.

**Comment by BrendaEgeland** [comment]
Thank you!

**Comment by adavidw** [comment]
I will soon rev the version of the overall repo and get a new gem cut, but I want to make sure any other pressing fixes are included and that everything works correctly. I want to cut _one_ new gem, not a whole bunch :).

**Comment by gregawoods** [comment]
Thank you @adavidw! Any chance https://github.com/AuthorizeNet/sdk-ruby/pull/116 could be included in that? Rails 5 users are not able to upgrade to the latest gem version currently.

**Pull request closed without merging**
