### PR TITLE
Allow opaque data to be passed in an arb creation

### PR DESCRIPTION
**Pull request by jsteel**

### CODE REVIEW

**Comment by mikewagz** [comment]
Is there a workaround to submitting opaque payment data until this gets merged?

**Comment by jsteel** [comment]
Not that I know of. I'm quite shocked nobody has run into this before. I'm guessing Ruby users normally go with Stripe, so nobody has ever encountered this before.

**Comment by rahulrnitc** [comment]
Hi @mikewagz,
You can use the new way of creating subscription, here is the sample code for the same - https://github.com/AuthorizeNet/sample-code-ruby/blob/master/RecurringBilling/create-subscription.rb
For passing opaque datatype you can use 
`PaymentType.new(:opaqueData => OpaqueDataType.new('COMMON.ACCEPT.INAPP.PAYMENT','9479246682350209005001',nil) )` 

Authorize.net is only accepting this type of opaque data(COMMON.ACCEPT.INAPP.PAYMENT) for ARB.

**Comment by mikewagz** [comment]
@rahulrnitc, 

Thanks, I'm trying to use this on a CreateTransactionRequest (not a subscription).  I had seen that in the subscriptions section and tried it with the transaction, but it does not work.  Here's the relevant part of my request (note I use the newer colon syntax instead of hash-rocket syntax in your example):

```
    req = CreateTransactionRequest.new
    req.transactionRequest = TransactionRequestType.new()
    req.transactionRequest.amount = amount
    req.transactionRequest.payment = PaymentType.new(opaqueData: OpaqueDataType.new('COMMON.ACCEPT.INAPP.PAYMENT', params[:opaque_payment], nil))
    req.transactionRequest.transactionType = TransactionTypeEnum::AuthCaptureTransaction
```


The Ruby SDK defaults it to a credit card payment.  In the request, the payment object looks like this:

```
  @payment=
    #<AuthorizeNet::API::PaymentType:0x007ffe9dc404e8
     @bankAccount=nil,
     @creditCard=
      {:opaqueData=>
        #<AuthorizeNet::API::OpaqueDataType:0x007ffe9dc40538
         @dataDescriptor="COMMON.ACCEPT.INAPP.PAYMENT",
         @dataKey=nil,
         @dataValue="9483460850245027905001">},
     @emv=nil,
     @encryptedTrackData=nil,
     @opaqueData=nil,
     @payPal=nil,
     @trackData=nil>,
```

This results in an error in the response:

```
  @text=
       "The element 'creditCard' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' cannot contain text. List of possible elements expected: 'cardNumber' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.">],
   @resultCode="Error",
```

It looks like some SDK code [here](https://github.com/AuthorizeNet/sdk-ruby/blob/master/lib/authorize_net/transaction.rb) only accepts either eCheck or Credit Card:

```
  def handle_payment_argument(payment)
      case payment
      when AuthorizeNet::CreditCard, AuthorizeNet::ECheck
        set_fields(payment.to_hash)
      else
        set_fields(:card_num => payment)
      end
    end
```

Although I could be mistaken, as I haven't dug through the API and SDK enough.

Is there something I'm missing?

**Comment by rahulrnitc** [comment]
Hi @mikewagz 
You can find working sample code using 'COMMON.ACCEPT.INAPP.PAYMENT'  here: https://github.com/AuthorizeNet/sample-code-ruby/blob/master/MobileInappTransactions/create-an-accept-transaction.rb

**Comment by starrychloe** [comment]
@mikewagz You can't pass parameters into new. You can't do

    req.transactionRequest.payment = PaymentType.new(opaqueData: OpaqueDataType.new('COMMON.ACCEPT.INAPP.PAYMENT', params[:opaque_payment], nil))

You have to do

    my_opaque_data = ...
    payment = PaymentType.new
    payment.opaqueData = my_opaque_data

See https://github.com/AuthorizeNet/sdk-ruby/issues/143

The SDK leaves a lot to be desired.

**Comment by chsriniv9** [comment]
Closing this, as the PR is linked to deprecated Methods of the SDK. This support has been added in the latest [sdk version 1.9.5](https://github.com/AuthorizeNet/sdk-ruby/releases/tag/1.9.5)

**Pull request closed without merging**
