### PR TITLE
Allow using with Rails 5 (ActiveSupport >= 4.2.6)

### PR DESCRIPTION
**Pull request by ericboehs**

### CODE REVIEW

**Comment by sunnyrajrathod** [comment]
Thanks for the PR.

**Comment by phlcastro** [comment]
@sunnyrajrathod any plans to release it soon?

**Comment by sunnyrajrathod** [comment]
Hi @phlcastro ,
We will update the SDK within early next week.

**Comment by ericboehs** [comment]
Is there anything I can do to help get this merged? Thanks!

**Comment by sunnyrajrathod** [comment]
Please check the latest release https://rubygems.org/gems/authorizenet/versions/1.9.0.2. 
Let us know in case of any issues. Thanks!

**Comment by ericboehs** [comment]
Thanks so much! Cheers!

**Comment by ericboehs** [comment]
@sunnyrajrathod Hmm this didn't seem to work. It looks like you can't do conditional gemspecs with Bundler.

I think you just have to relax your version dependency on activesupport. I believe your reasoning for keeping the older 4.2.6 around was to support older versions of ruby. For those users, you could add a recommendation to lock the activesupport gem to 4.2.6.

**Comment by sunnyrajrathod** [comment]
Sorry for the inconvenience. We are working on fixing this.

**Comment by ericboehs** [comment]
What's the planned fix here? The version relaxing?

**Comment by ericboehs** [comment]
@sunnyrajrathod Still working on the fix here?

**Pull request closed without merging**
