### PR TITLE
Update ruby versions in travis config

### PR DESCRIPTION
**Pull request by lostapathy**
Removal ruby 2.1 as it has EOL'd, update ruby 2.2 and 2.3 to current versions

### CODE REVIEW

**Comment by namanbansal** [comment]
Thanks @lostapathy ! I have added the mentioned versions to the travis.yml.

**Comment by lostapathy** [comment]
Thanks for adding the updated versions.  For curiosity sake - why do we need to keep the old versions in the build, especially the EOL'd ruby 2.1?

**Comment by adavidw** [comment]
Definitely don't need 2.1 anymore. For PCI-DSS compliance reasons we generally wouldn't want to support any of our tools on software that doesn't receive security updates. We'll make the change here at some point.

**Comment by lostapathy** [comment]
Thanks @adavidw  - I will close this, as this was just a question at this point.  #116 is much more important to fix this gem, and #117 would be great to help ensure things don't get broken again.

**Pull request closed without merging**
