### PR TITLE
Fix type for customerProfileId

### PR DESCRIPTION
**Pull request by ianneub**
`customerProfileId` should not be a `NumericStringsType`, it is a simple string.

This will fix the issue in #180 .

### CODE REVIEW

**Comment by tjbarber** [comment]
Is there any reason why this is not being accepted? Seems like a reasonable and easy fix.

**Comment by hallmatt** [comment]
Hey @gnongsie - can we get this PR merged into master? Seems to be a good fix for #180

**Comment by gnongsie** [comment]
We are relying on the API specification / XSD as the source of truth, and not the documentation, which may be a bit delayed in updating the details.
In any case, the docs are also in agreement that this field should be a numericString.
I am closing this PR as I do not see it as valid anymore.

**Comment by gnongsie** [comment]
Actually, correction. I must apologize here.
This change is valid and I will include it in my own pull request.

**Pull request closed without merging**
